#ifndef FRACTION_H_INCLUDED
#define FRACTION_H_INCLUDED

Fraction detect();
Fractiscanf("%i %c %i",&frac1.num,&a,&frac1.denom);on PGCD(Fraction frac);
Fraction addition(Fraction fraca, Fraction fracb);
Fraction soustraction(Fraction fraca, Fraction fracb);
Fraction multiplication(Fraction fraca, Fraction fracb);
Fraction division(Fraction fraca, Fraction fracb);
Fraction affichage (Fraction Fracresult);
Fraction operation(int ope, Fraction frac1, Fraction frac2);
void menu();
#endif // FRACTION_H_INCLUDED
